spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bootcamp
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql